### ISSUE TITLE
From value is not getting set

### ISSUE THREAD

**Issue by mattdelacdev** [wwwouter/wercker-step-email-notify#1]
I tried with this step and mies' one and none seems to be setting the sender email address correctly.

Here is my step description:

``` yaml
after-steps:
      - wouter/email-notify:
          from: matt@fliplingo.com
          to: matt@fliplingo.com
          username: $MANDRILL_USERNAME
          password: $MANDRILL_PASSWORD
          host: smtp.mandrillapp.com:587
          on: always
```

and this is what Mandrill gets:

``` yaml
{
    "from_name": null,
    "to": [
        "matt@fliplingo.com"
    ],
    "key": "xxxxxxxxxxxxx",
    "async": false,
    "from_email": null,
    "raw_message": "xxxxxxxxxxx"
}
```

The email gets rejected because the form `form_email` value is `null`. Not exactly sure which side is faulty since I can't get more information. Am I doing something wrong?

And here is the step log output:

```
cd $WERCKER_SOURCE_DIR
ubuntu$/pipeline/build$ export WERCKER_STEP_ROOT="/wercker/steps/wouter/email-notify/0.0.3"
ubuntu$/pipeline/build$ export WERCKER_STEP_ID="57b61cb3-2348-40e8-a590-7831849974a6"
ubuntu$/pipeline/build$ export WERCKER_STEP_NAME="email-notify"
ubuntu$/pipeline/build$ export WERCKER_REPORT_NUMBERS_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/numbers.ini"
ubuntu$/pipeline/build$ export WERCKER_REPORT_MESSAGE_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/message.txt"
ubuntu$/pipeline/build$ export WERCKER_REPORT_ARTIFACTS_DIR="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/artifacts"
ubuntu$/pipeline/build$ mkdir -p $WERCKER_REPORT_ARTIFACTS_DIR
ubuntu$/pipeline/build$ export WERCKER_STEP_TEMP="/tmp/$WERCKER_STEP_ID"
ubuntu$/pipeline/build$ mkdir -p $WERCKER_STEP_TEMP
ubuntu$/pipeline/build$ source '/wercker/wercker-build-essentials/init.sh'
ubuntu$/pipeline/build$ export WERCKER_EMAIL_NOTIFY_FROM="matt@fliplingo.com"
ubuntu$/pipeline/build$ export WERCKER_EMAIL_NOTIFY_TO="matt@fliplingo.com"
ubuntu$/pipeline/build$ export WERCKER_EMAIL_NOTIFY_USERNAME="$MANDRILL_USERNAME"
ubuntu$/pipeline/build$ export WERCKER_EMAIL_NOTIFY_PASSWORD="$MANDRILL_PASSWORD"
ubuntu$/pipeline/build$ export WERCKER_EMAIL_NOTIFY_HOST="smtp.mandrillapp.com:587"
ubuntu$/pipeline/build$ export WERCKER_EMAIL_NOTIFY_ON="always"
ubuntu$/pipeline/build$ source "$WERCKER_STEP_ROOT/run.sh"
ubuntu$/pipeline/build$
```
